### ISSUE TITLE
Problems with frame aquisition after some hours of camera running

### ISSUE THREAD

**Issue by Westerby** [pieye/nimbus-python#6]
Hello,

After ca. 2-4 hours of development (non-constant running) frame aquisition rate visibly drops, and I frequently get the following error: 

```
The coroutine raised an exception:
Traceback (most recent call last):
  File "...\nimbusPython\NimbusClient.py", line 223, in _pollQueue
    image = await asyncio.wait_for(self._imageQueue.get(), timeout=self._rcvTimeout)
  File "...\lib\asyncio\tasks.py", line 423, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
```

Camera is unable to operate normally for some time.

My guess is it can be attributed to the rising temperature of the sensor. If you confirm:
- is there a recommended safe temperature operation range? 
- I can add additional cooling, like radiatior or ventilator. Is there a recommended way of doing this?

My camera is placed directly on Raspberry, without additional housing, in a well ventilated room.

By the way the what exaclty does temperature shows? Temperature of the vision sensor?

Best

**Comment by bjajoh** [comment]
Hi,

what exposure mode are you using? Can you have a look at the temperatures? (You can see them in "nimbus-web")

- The temperature should stay below 75°C, the automatic exposure mode has a temperature control. However using the manual exposure, the user need to careful and monitor it.
- Without a housing it should be fine, unless you use the highest exposure setting for a long time. A simple fan with consistent airflow around the illumination LEDs should be the way to go, but it usually not required without a housing.

The temperature is measured directly on the PCB and should state the heat exposure of the vision sensor.

Let me know if you have any question.

Best, 
Bjarne

**Comment by Westerby** [comment]
Hello,
thanks for the info. We use manual setting. OK, we'll try to monitor the temperature, use the cooling if needed, and let know.

Best
Westerby

**Comment by bjajoh** [comment]
Hi,

perfect! Let me know if you have any questions or need support.

Best,
Bjarne
